---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:mishalipatnikov/lighthouse-role.git
    scm: git
    name: lighthouse

  - src: git@github.com:mishalipatnikov/vector-role.git
    scm: git
    name: vector
