---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - clickhouse

- name: Install Lighthouse
  hosts: lighthouse
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - lighthouse

- name: Install Vector
  hosts: vector
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - vector