---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted

    - name: Restart Vector
      become: true
      ansible.builtin.service:
         name: vector
         state: restarted
   
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install clickhouse
      apt:
        name: "{{ item }}" #={{ clickhouse_version }}"
        state: present
      loop: "{{ clickhouse_packages }}"


    - name: Create database
      command: 
        cmd: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0


- name: Install Vector
  hosts: vector
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  handlers:
    - name: Start Vector
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Download Vector setup script
      get_url:
        url: https://setup.vector.dev
        dest: /etc/vector_setup.sh

    - name: Run Vector setup script
      shell: bash /etc/vector_setup.sh
      args:
        warn: false

    - name: Install vector
      apt:
        name: "vector" #={{ vector_version }}"
        state: present
      become: true
    - name: Configure Vector
      template:
        src: vector.yaml.j2
        dest: /etc/vector/vector.yaml
      notify: Start Vector


- name: Install Lighthouse
  hosts: lighthouse  # Replace with your target host
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Install required packages
      apt:
        name:
          - git
          - nginx  
        state: present
        update_cache: yes

    - name: Clone Lighthouse repository
      git:
        repo: https://github.com/VKCOM/lighthouse.git
        dest: /var/www/lighthouse  

    - name: Configure Nginx to serve Lighthouse
      copy:
        dest: /etc/nginx/sites-available/lighthouse
        content: 
          server {
              listen 80;
              {{ ansible_host }};  

              location / {
                  root /var/www/lighthouse;
                  index index.html;
                  try_files $uri $uri/ =404;
              }
          }

    - name: Enable Lighthouse site in Nginx
      command: nginx -s reload
      notify:
        - Restart Nginx

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted